apiVersion: v1
kind: Service
metadata:
  labels:
    app: springbootapp
  name: myspringbootapp
spec:
  ports:
  - nodePort: 32586
    port: 3010
    protocol: TCP
    targetPort: 3010
  selector:
    app: springbootapp
  type: NodePort
